//#############################################################################
//
// FILE:   vienna_user_settings.h
//
// TITLE:  vienna User Settings
//
//#############################################################################
// $TI Release: TIDM_1000 v4.01.05.00 $
// $Release Date: Thu Dec 14 13:12:56 CST 2023 $
// $Copyright:
// Copyright (C) 2023 Texas Instruments Incorporated - http://www.ti.com/
//
// ALL RIGHTS RESERVED
// $
//#############################################################################
#define VIENNA_INSTRUMENTATION_ISR_RUNNING_ON C28x_CORE

//
// Make sure the LSP CLK frequency is correctly set as part of Device_init()
// function in device.c file
//
#define VIENNA_LSP_CLK_FREQUENCY_HZ ((float32_t)50 * 1000000)
#define VIENNA_C28x_ISR1_INTERRUPT_PIE_GROUP_NO INTERRUPT_ACK_GROUP3
#define VIENNA_C28x_ISR2_INTERRUPT_PIE_GROUP_NO INTERRUPT_ACK_GROUP14

#define VIENNA_C28x_ISR1_INTERRUPT_TRIG_PWM_BASE EPWM1_BASE
#define VIENNA_C28x_ISR1_INTERRUPT INT_EPWM1
#define VIENNA_CLA_ISR1_TRIG  CLA_TRIGGER_EPWM1INT

#define VIENNA_INSTRUMENTATION_ISR_FREQUENCY_HZ ((float32_t)10 * 1000)
#define VIENNA_C28x_INSTRUMENTATION_INTERRUPT_TRIG_CPUTIMER_BASE CPUTIMER2_BASE
#define VIENNA_C28x_INSTRUMENTATION_INTERRUPT INT_TIMER2

//
// set the time base for CPU Timers in Hz
// Timer 0 & 1  are used for background tasks, non timing critical
// Timer 2 is used for instrumentation ISR
//
#define VIENNA_CPU_TIMER0_FREQ_HZ ((float32_t)100)
#define VIENNA_CPU_TIMER1_FREQ_HZ ((float32_t)10)
#define VIENNA_CPU_TIMER2_FREQ_HZ VIENNA_INSTRUMENTATION_ISR_FREQUENCY_HZ

//
// 1 for SDFM sensing
// 0 otherwise
//
#define VIENNA_SDFM_SENSING 0
#define VIENNA_I_MAX_SENSE_SD_AMPS ((float32_t)20.1)

#define VIENNA_GV_PI_MAX   ((float32_t)0.7)
#define VIENNA_GV_PI_MIN   ((float32_t)-0.02)
#define VIENNA_NON_LINEAR_V_LOOP_KP_MULTIPLIER ((float32_t)5.0)

#define VIENNA_VBUS_TRIP_LIMIT_VOLTS ((float32_t)720.0)

//
// PWM Related
//
#define VIENNA_HIGH_FREQ_PWM1_BASE                 EPWM1_BASE

#define VIENNA_HIGH_FREQ_PWM1_H_GPIO                 0
#define VIENNA_HIGH_FREQ_PWM1_H_GPIO_PIN_CONFIG      GPIO_0_EPWM1A
//#define HIGH_FREQ_PWM1_H_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_0_GPIO0

#define VIENNA_HIGH_FREQ_PWM1_L_GPIO                 1
#define VIENNA_HIGH_FREQ_PWM1_L_GPIO_PIN_CONFIG      GPIO_1_EPWM1B
//#define HIGH_FREQ_PWM1_L_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_1_GPIO1

#define VIENNA_HIGH_FREQ_PWM2_BASE                 EPWM2_BASE

#define VIENNA_HIGH_FREQ_PWM2_H_GPIO               2
#define VIENNA_HIGH_FREQ_PWM2_H_GPIO_PIN_CONFIG    GPIO_2_EPWM2A
#define VIENNA_HIGH_FREQ_PWM2_H_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_2_GPIO2

#define VIENNA_HIGH_FREQ_PWM2_L_GPIO               3
#define VIENNA_HIGH_FREQ_PWM2_L_GPIO_PIN_CONFIG    GPIO_3_EPWM2B
#define VIENNA_HIGH_FREQ_PWM2_L_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_3_GPIO3

#define VIENNA_HIGH_FREQ_PWM3_BASE                 EPWM3_BASE

#define VIENNA_HIGH_FREQ_PWM3_H_GPIO               4
#define VIENNA_HIGH_FREQ_PWM3_H_GPIO_PIN_CONFIG    GPIO_4_EPWM3A
#define VIENNA_HIGH_FREQ_PWM3_H_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_4_GPIO4

#define VIENNA_HIGH_FREQ_PWM3_L_GPIO               5
#define VIENNA_HIGH_FREQ_PWM3_L_GPIO_PIN_CONFIG    GPIO_5_EPWM3B
#define VIENNA_HIGH_FREQ_PWM3_L_PHASE_SHEDDING_GPIO_PIN_CONFIG      GPIO_5_GPIO5

//
//ADC Related
//
#define VIENNA_ADC_TRIG_SOURCE     ADC_TRIGGER_EPWM1_SOCA
#define VIENNA_ADC_CONV_TIME       ((float32_t)0.000000210)

#define VIENNA_IL1_ADC_MODULE           ADCA_BASE
#define VIENNA_IL1_ADC_PIN              ADC_CH_ADCIN2
#define VIENNA_IL1_ADC_TRIG_SOURCE      VIENNA_ADC_TRIG_SOURCE
#define VIENNA_IL1_ACQPS_SYS_CLKS       ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_IL1_ADCRESULTREGBASE     ADCARESULT_BASE

#define VIENNA_IL1_ADC_SOC_NO_1         ADC_SOC_NUMBER0

#define VIENNA_IL1_ADC_SOC_NO_2         ADC_SOC_NUMBER3

#define VIENNA_IL1_ADC_SOC_NO_3         ADC_SOC_NUMBER6

#define VIENNA_IL1_ADC_SOC_NO_4         ADC_SOC_NUMBER9

#define VIENNA_IL2_ADC_MODULE           ADCA_BASE
#define VIENNA_IL2_ADC_PIN              ADC_CH_ADCIN4
#define VIENNA_IL2_ADC_TRIG_SOURCE      VIENNA_ADC_TRIG_SOURCE
#define VIENNA_IL2_ACQPS_SYS_CLKS       ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_IL2_ADCRESULTREGBASE     ADCARESULT_BASE

#define VIENNA_IL2_ADC_SOC_NO_1         ADC_SOC_NUMBER1

#define VIENNA_IL2_ADC_SOC_NO_2         ADC_SOC_NUMBER4

#define VIENNA_IL2_ADC_SOC_NO_3         ADC_SOC_NUMBER7

#define VIENNA_IL2_ADC_SOC_NO_4         ADC_SOC_NUMBER10

#define VIENNA_IL3_ADC_MODULE           ADCA_BASE
#define VIENNA_IL3_ADC_PIN              ADC_CH_ADCIN14
#define VIENNA_IL3_ADC_TRIG_SOURCE      VIENNA_ADC_TRIG_SOURCE
#define VIENNA_IL3_ACQPS_SYS_CLKS       ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_IL3_ADCRESULTREGBASE     ADCARESULT_BASE

#define VIENNA_IL3_ADC_SOC_NO_1         ADC_SOC_NUMBER2

#define VIENNA_IL3_ADC_SOC_NO_2         ADC_SOC_NUMBER5

#define VIENNA_IL3_ADC_SOC_NO_3         ADC_SOC_NUMBER8

#define VIENNA_IL3_ADC_SOC_NO_4         ADC_SOC_NUMBER11

#define VIENNA_V1_ADC_MODULE            ADCB_BASE
#define VIENNA_V1_ADC_PIN               ADC_CH_ADCIN2
#define VIENNA_V1_ADC_TRIG_SOURCE       VIENNA_ADC_TRIG_SOURCE
#define VIENNA_V1_ACQPS_SYS_CLKS        ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_V1_ADCRESULTREGBASE      ADCBRESULT_BASE

#define VIENNA_V1_ADC_SOC_NO_1          ADC_SOC_NUMBER0
#define VIENNA_V1_ADC_SOC_NO_2          ADC_SOC_NUMBER1
#define VIENNA_V1_ADC_SOC_NO_3          ADC_SOC_NUMBER2
#define VIENNA_V1_ADC_SOC_NO_4          ADC_SOC_NUMBER3

#define VIENNA_V2_ADC_MODULE            ADCD_BASE
#define VIENNA_V2_ADC_PIN               ADC_CH_ADCIN0
#define VIENNA_V2_ADC_TRIG_SOURCE       VIENNA_ADC_TRIG_SOURCE
#define VIENNA_V2_ACQPS_SYS_CLKS        ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_V2_ADCRESULTREGBASE      ADCDRESULT_BASE

#define VIENNA_V2_ADC_SOC_NO_1          ADC_SOC_NUMBER0
#define VIENNA_V2_ADC_SOC_NO_2          ADC_SOC_NUMBER2
#define VIENNA_V2_ADC_SOC_NO_3          ADC_SOC_NUMBER4
#define VIENNA_V2_ADC_SOC_NO_4          ADC_SOC_NUMBER6

#define VIENNA_V3_ADC_MODULE            ADCD_BASE
#define VIENNA_V3_ADC_PIN               ADC_CH_ADCIN2
#define VIENNA_V3_ADC_TRIG_SOURCE       VIENNA_ADC_TRIG_SOURCE
#define VIENNA_V3_ACQPS_SYS_CLKS        ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_V3_ADCRESULTREGBASE      ADCDRESULT_BASE

#define VIENNA_V3_ADC_SOC_NO_1          ADC_SOC_NUMBER1
#define VIENNA_V3_ADC_SOC_NO_2          ADC_SOC_NUMBER3
#define VIENNA_V3_ADC_SOC_NO_3          ADC_SOC_NUMBER5
#define VIENNA_V3_ADC_SOC_NO_4          ADC_SOC_NUMBER7

#define VIENNA_VBUSPM_ADC_MODULE        ADCC_BASE
#define VIENNA_VBUSPM_ADC_PIN           ADC_CH_ADCIN2
#define VIENNA_VBUSPM_ADC_TRIG_SOURCE   VIENNA_ADC_TRIG_SOURCE
#define VIENNA_VBUSPM_ACQPS_SYS_CLKS    ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_VBUSPM_ADCRESULTREGBASE  ADCCRESULT_BASE

#define VIENNA_VBUSPM_ADC_SOC_NO_1      ADC_SOC_NUMBER0
#define VIENNA_VBUSPM_ADC_SOC_NO_2      ADC_SOC_NUMBER2
#define VIENNA_VBUSPM_ADC_SOC_NO_3      ADC_SOC_NUMBER4
#define VIENNA_VBUSPM_ADC_SOC_NO_4      ADC_SOC_NUMBER6

#define VIENNA_VBUSMN_ADC_MODULE        ADCC_BASE
#define VIENNA_VBUSMN_ADC_PIN           ADC_CH_ADCIN4
#define VIENNA_VBUSMN_ADC_TRIG_SOURCE   VIENNA_ADC_TRIG_SOURCE
#define VIENNA_VBUSMN_ACQPS_SYS_CLKS    ((float32_t)100.0 * (float32_t)0.000000001 * (float32_t)VIENNA_CPU_SYS_CLOCK_FREQ_HZ)
#define VIENNA_VBUSMN_ADCRESULTREGBASE  ADCCRESULT_BASE

#define VIENNA_VBUSMN_ADC_SOC_NO_1      ADC_SOC_NUMBER1
#define VIENNA_VBUSMN_ADC_SOC_NO_2      ADC_SOC_NUMBER3
#define VIENNA_VBUSMN_ADC_SOC_NO_3      ADC_SOC_NUMBER5
#define VIENNA_VBUSMN_ADC_SOC_NO_4      ADC_SOC_NUMBER7

//
//CMPSS related
//
#define VIENNA_BOARD_PROT_IL1_CUR 1

#define VIENNA_BOARD_PROT_IL1_CUR_CMPSS_BASE      CMPSS1_BASE

#define VIENNA_BOARD_PROT_IL1_CUR_XBAR_MUX        XBAR_MUX00
#define VIENNA_BOARD_PROT_IL1_CUR_XBAR_MUX_VAL    XBAR_EPWM_MUX00_CMPSS1_CTRIPH_OR_L

#define VIENNA_BOARD_PROT_IL2_CUR 1

#define VIENNA_BOARD_PROT_IL2_CUR_CMPSS_BASE      CMPSS2_BASE

#define VIENNA_BOARD_PROT_IL2_CUR_XBAR_MUX        XBAR_MUX02
#define VIENNA_BOARD_PROT_IL2_CUR_XBAR_MUX_VAL    XBAR_EPWM_MUX02_CMPSS2_CTRIPH_OR_L

#define VIENNA_BOARD_PROT_IL3_CUR 1

#define VIENNA_BOARD_PROT_IL3_CUR_CMPSS_BASE      CMPSS4_BASE

#define VIENNA_BOARD_PROT_IL3_CUR_XBAR_MUX        XBAR_MUX06
#define VIENNA_BOARD_PROT_IL3_CUR_XBAR_MUX_VAL    XBAR_EPWM_MUX06_CMPSS4_CTRIPH_OR_L

//
//SDFM Related
//
#define VIENNA_SDFM_CMPSS_OSR 32
#define VIENNA_SDFM_CMPSS_MAX_VAL VIENNA_SDFM_CMPSS_OSR * VIENNA_SDFM_CMPSS_OSR * VIENNA_SDFM_CMPSS_OSR
#define VIENNA_SDFM_CMPSS_MAX_VAL_DIV_2 ((uint16_t)VIENNA_SDFM_CMPSS_MAX_VAL / 2)

//
// SDFM Sensing Parameters
//
#define VIENNA_SDCLK_FREQ_HZ       ((float32_t)(20 * 1000000))
#define VIENNA_SD_CLK_COUNT VIENNA_ECAPSYSCLOCK_FREQ_HZ / VIENNA_SDCLK_FREQ_HZ
#define VIENNA_PWM_CLK_IN_SDFM_CLK (int16_t)((float32_t)VIENNA_PWMSYSCLOCK_FREQ_HZ / (float32_t)VIENNA_SDCLK_FREQ_HZ)
#define VIENNA_PWM_CLK_IN_SDFM_OSR (int16_t)((float32_t)VIENNA_PWM_CLK_IN_SDFM_CLK * (float32_t)VIENNA_SDFM_OSR)
#define VIENNA_SDFM_FILTER_TYPE    3
#define VIENNA_SDFM_OSR            100

//
// SDFM PINS & FILTERS
//
#define VIENNA_IL1_SDFM_BASE                    SDFM1_BASE
#define VIENNA_IL1_SDFM_FILTER                  SDFM_FILTER_1
#define VIENNA_GPIO_IL1_SDFM_DATA               48
#define VIENNA_GPIO_IL1_SDFM_DATA_PIN_CONFIG    GPIO_48_SD1_D1
#define VIENNA_GPIO_IL1_SDFM_CLOCK              49
#define VIENNA_GPIO_IL1_SDFM_CLOCK_PIN_CONFIG   GPIO_49_SD1_C1
#define VIENNA_IL2_SDFM_BASE                    SDFM1_BASE
#define VIENNA_IL2_SDFM_FILTER                  SDFM_FILTER_2
#define VIENNA_GPIO_IL2_SDFM_DATA               50
#define VIENNA_GPIO_IL2_SDFM_DATA_PIN_CONFIG    GPIO_50_SD1_D2
#define VIENNA_GPIO_IL2_SDFM_CLOCK              51
#define VIENNA_GPIO_IL2_SDFM_CLOCK_PIN_CONFIG   GPIO_51_SD1_C2
#define VIENNA_IL3_SDFM_BASE                    SDFM1_BASE
#define VIENNA_IL3_SDFM_FILTER                  SDFM_FILTER_3
#define VIENNA_GPIO_IL3_SDFM_DATA               52
#define VIENNA_GPIO_IL3_SDFM_DATA_PIN_CONFIG    GPIO_52_SD1_D3
#define VIENNA_GPIO_IL3_SDFM_CLOCK              53
#define VIENNA_GPIO_IL3_SDFM_CLOCK_PIN_CONFIG   GPIO_53_SD1_C3


#define VIENNA_IL1_SDFM_SENSE_XBAR_MUX_VAL      XBAR_EPWM_MUX16_SD1FLT1_COMPH_OR_COMPL
#define VIENNA_IL1_SDFM_SENSE_XBAR_MUX          XBAR_MUX16

#define VIENNA_IL2_SDFM_SENSE_XBAR_MUX_VAL      XBAR_EPWM_MUX18_SD1FLT2_COMPH_OR_COMPL
#define VIENNA_IL2_SDFM_SENSE_XBAR_MUX          XBAR_MUX18

#define VIENNA_IL3_SDFM_SENSE_XBAR_MUX_VAL      XBAR_EPWM_MUX20_SD1FLT3_COMPH_OR_COMPL
#define VIENNA_IL3_SDFM_SENSE_XBAR_MUX          XBAR_MUX20

//
// SDFM Clock Generation
// ECAP1 is used to come out at OUTPUTXBAR1, on pin 24
//
#define VIENNA_SDFM_CLK_SOURCE_BASE ECAP1_BASE
#define VIENNA_SDFM_CLK_GPIO 24
#define VIENNA_SDFM_CLK_PIN_CONFIG GPIO_24_OUTPUTXBAR1
#define VIENNA_SDFM_CLK_OUTPUTXBAR XBAR_OUTPUT1
#define VIENNA_SDFM_CLK_OUTPUTXBAR_MUX XBAR_MUX00
#define VIENNA_SDFM_CLK_OUTPUTXBAR_MUX_CONFIG XBAR_OUT_MUX00_ECAP1_OUT

//
//GPIO Related
//
#define VIENNA_GPIO_PROFILING1 12
#define VIENNA_GPIO_PROFILING1_SET GPIO_GPASET_GPIO12
#define VIENNA_GPIO_PROFILING1_CLEAR GPIO_GPACLEAR_GPIO12
#define VIENNA_GPIO_PROFILING1_PIN_CONFIG GPIO_12_GPIO12

#define VIENNA_GPIO_PROFILING2 13
#define VIENNA_GPIO_PROFILING2_SET GPIO_GPASET_GPIO13
#define VIENNA_GPIO_PROFILING2_CLEAR GPIO_GPACLEAR_GPIO13
#define VIENNA_GPIO_PROFILING2_PIN_CONFIG GPIO_13_GPIO13

#define VIENNA_GPIO_LED1 31
#define VIENNA_GPIO_LED1_SET GPIO_GPASET_GPIO31
#define VIENNA_GPIO_LED1_CLEAR GPIO_GPACLEAR_GPIO31
#define VIENNA_GPIO_LED1_PIN_CONFIG GPIO_31_GPIO31

#define VIENNA_GPIO_LED2 34
#define VIENNA_GPIO_LED2_SET GPIO_GPASET_GPIO34
#define VIENNA_GPIO_LED2_CLEAR GPIO_GPACLEAR_GPIO34
#define VIENNA_GPIO_LED2_PIN_CONFIG GPIO_34_GPIO34

//
// SFRA related
//
#define VIENNA_SFRA_GUI_SCI_BASE SCIA_BASE
#define VIENNA_SCI_VBUS_CLK ((float32_t)50 * 1000000)
#define VIENNA_SFRA_GUI_SCI_BAUDRATE 57600

#define VIENNA_SFRA_GUI_SCIRX_GPIO 28
#define VIENNA_SFRA_GUI_SCITX_GPIO 29

#define VIENNA_SFRA_GUI_SCIRX_GPIO_PIN_CONFIG GPIO_28_SCIRXDA
#define VIENNA_SFRA_GUI_SCITX_GPIO_PIN_CONFIG GPIO_29_SCITXDA

//
// if the following #define is set to 1 SFRA GUI indicates status on an LED
// otherwise LED code is ignored
//
#define VIENNA_SFRA_GUI_LED_INDICATOR 1
#define VIENNA_SFRA_GUI_LED_GPIO 31
#define VIENNA_SFRA_GUI_LED_GPIO_PIN_CONFIG GPIO_31_GPIO31

//
// Add any system specific setting below
//
#if VIENNA_SFRA_TYPE == VIENNA_SFRA_VOLTAGE || VIENNA_SFRA_TYPE == VIENNA_SFRA_BALANCECNTL
#define VIENNA_SFRA_FREQ_START 2
#define VIENNA_SFRA_FREQ_LENGTH 30

//
//SFRA step Multiply = 10^(1/No of steps per decade(40))
//
#define VIENNA_SFRA_FREQ_STEP_MULTIPLY ((float32_t)1.08)
#define VIENNA_SFRA_AMPLITUDE ((float32_t)0.003)
#elif VIENNA_SFRA_TYPE == VIENNA_SFRA_CURRENT  // current loop
#define VIENNA_SFRA_FREQ_START 200
#define VIENNA_SFRA_FREQ_LENGTH 100

//
//SFRA step Multiply = 10^(1/No of steps per decade(40))
//
#define VIENNA_SFRA_FREQ_STEP_MULTIPLY ((float32_t)1.045)
#define VIENNA_SFRA_AMPLITUDE ((float32_t)0.01)
#endif

//
// check sfra_gui_scicomms_driverlib.c file for defines used by SCI CommsSFRA GUI
//
